package pojo;
// Generated Aug 18, 2012 5:14:49 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Device generated by hbm2java
 */
public class Device implements java.io.Serializable {

    private Integer id;
    private Lab lab;
    private String name;
    private Date createDate;
    private Date warranty;
    private String description;
    private Boolean endWarranty;
    private Boolean isProlem;
    private String status;
    private Set<Report> reports = new HashSet<Report>(0);

    public Device() {
    }

    public Device(Integer id, String name, String status) {
        this.id = id;
        this.name = name;
        this.status = status;
    }
   public String getGrade() {
        if ("Activate".equalsIgnoreCase(this.status)) {
            return "gradeC";
        } else {
            return "gradeX";
        }
    }
    public Device(Integer id, Lab lab, String name, Date createDate, Date warranty, String description, Boolean endWarranty, Boolean isProlem, String status, Set<Report> reports) {
        this.id = id;
        this.lab = lab;
        this.name = name;
        this.createDate = createDate;
        this.warranty = warranty;
        this.description = description;
        this.endWarranty = endWarranty;
        this.isProlem = isProlem;
        this.status = status;
        this.reports = reports;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

 

    public Lab getLab() {
        return this.lab;
    }

    public void setLab(Lab lab) {
        this.lab = lab;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Date getWarranty() {
        return this.warranty;
    }

    public void setWarranty(Date warranty) {
        this.warranty = warranty;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Boolean getEndWarranty() {
        return this.endWarranty;
    }

    public void setEndWarranty(Boolean endWarranty) {
        this.endWarranty = endWarranty;
    }

    public Boolean getIsProlem() {
        return this.isProlem;
    }

    public void setIsProlem(Boolean isProlem) {
        this.isProlem = isProlem;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Set<Report> getReports() {
        return this.reports;
    }

    public void setReports(Set<Report> reports) {
        this.reports = reports;
    }
    
    
}
