package pojo;
// Generated Aug 18, 2012 5:14:49 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Lab generated by hbm2java
 */
public class Lab implements java.io.Serializable {

    private String id;
    private String name;
    private Date createDate;
    private String description;
    private String status;
    private Set<SignLab> signLabs = new HashSet<SignLab>(0);
    private Set<Device> devices = new HashSet<Device>(0);
    private Set<Technical> technicals = new HashSet<Technical>(0);

    public Lab() {
    }

    public Lab(String id, String name, String status) {
        this.id = id;
        this.name = name;
        this.status = status;
    }
    public String getGrade() {
        if ("Activate".equalsIgnoreCase(this.status)) {
            return "gradeC";
        } else {
            return "gradeX";
        }
    }
    public Lab(String id, String name, Date createDate, String description, String status, Set<SignLab> signLabs, Set<Device> devices, Set<Technical> technicals) {
        this.id = id;
        this.name = name;
        this.createDate = createDate;
        this.description = description;
        this.status = status;
        this.signLabs = signLabs;
        this.devices = devices;
        this.technicals = technicals;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Set<SignLab> getSignLabs() {
        return this.signLabs;
    }

    public void setSignLabs(Set<SignLab> signLabs) {
        this.signLabs = signLabs;
    }

    public Set<Device> getDevices() {
        return this.devices;
    }

    public void setDevices(Set<Device> devices) {
        this.devices = devices;
    }

    public Set<Technical> getTechnicals() {
        return this.technicals;
    }

    public void setTechnicals(Set<Technical> technicals) {
        this.technicals = technicals;
    }
}
