package pojo;
// Generated Aug 18, 2012 5:14:49 PM by Hibernate Tools 3.2.1.GA

/**
 * Permission generated by hbm2java
 */
public class Permission implements java.io.Serializable {

    private int id;
    private Role role;
    private Group group;
    private User user;

    public Permission() {
    }

    public Permission(int id) {
        this.id = id;
    }

    public Permission(int id, Role role, Group group, User user) {
        this.id = id;
        this.role = role;
        this.group = group;
        this.user = user;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Role getRole() {
        return this.role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    public Group getGroup() {
        return this.group;
    }

    public void setGroup(Group group) {
        this.group = group;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }
}
