package pojo;
// Generated Aug 18, 2012 5:14:49 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

    private String id;
    private String password;
    private Date createDate;
    private String status;
    private String name;
    private Boolean sex;
    private Date dob;
    private String phone;
    private String email;
    private String address;
    private Set<Permission> permissions = new HashSet<Permission>(0);
    private Set<Report> reportsForTechnician = new HashSet<Report>(0);
    private Set<SignLab> signLabs = new HashSet<SignLab>(0);
    private Set<Technical> technicals = new HashSet<Technical>(0);
    private Set<Report> reportsForSender = new HashSet<Report>(0);


    private String groupName;
    private String roleName;

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    
    
    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    public String getRoleNameF(){
      
        Set<Permission> permissions = this.getPermissions();
         Role role = ((Permission) (permissions.toArray()[0])).getRole();
        return role.getName();
    }
    public String getGenderStr() {
        if (null != this.sex) {
            if (this.sex) {
            return "Male";
        } else {
            return "Female";
        }
        } else {
            return "N/A";
        }
        
    }
    
    public String getGrade() {
        if (this.status.equalsIgnoreCase("Disable")) {
            return "gradeX";
        } else {
            return "gradeC";
        }
    }
    
    public User() {
    }

    public User(String id, String password, String status) {
        this.id = id;
        this.password = password;
        this.status = status;
    }

    public User(String id, String password, Date createDate, String status, String name, Boolean sex, Date dob, String phone, String email, String address, Set<Permission> permissions, Set<Report> reportsForTechnician, Set<SignLab> signLabs, Set<Technical> technicals, Set<Report> reportsForSender) {
        this.id = id;
        this.password = password;
        this.createDate = createDate;
        this.status = status;
        this.name = name;
        this.sex = sex;
        this.dob = dob;
        this.phone = phone;
        this.email = email;
        this.address = address;
        this.permissions = permissions;
        this.reportsForTechnician = reportsForTechnician;
        this.signLabs = signLabs;
        this.technicals = technicals;
        this.reportsForSender = reportsForSender;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getSex() {
        return this.sex;
    }

    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    public Date getDob() {
        return this.dob;
    }

    public void setDob(Date dob) {
        this.dob = dob;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Set<Permission> getPermissions() {
        return this.permissions;
    }

    public void setPermissions(Set<Permission> permissions) {
        this.permissions = permissions;
    }

    public Set<Report> getReportsForTechnician() {
        return this.reportsForTechnician;
    }

    public void setReportsForTechnician(Set<Report> reportsForTechnician) {
        this.reportsForTechnician = reportsForTechnician;
    }

    public Set<SignLab> getSignLabs() {
        return this.signLabs;
    }

    public void setSignLabs(Set<SignLab> signLabs) {
        this.signLabs = signLabs;
    }

    public Set<Technical> getTechnicals() {
        return this.technicals;
    }

    public void setTechnicals(Set<Technical> technicals) {
        this.technicals = technicals;
    }

    public Set<Report> getReportsForSender() {
        return this.reportsForSender;
    }

    public void setReportsForSender(Set<Report> reportsForSender) {
        this.reportsForSender = reportsForSender;
    }

    @Override
    public String toString() {
        return "User{" + "id=" + id + ", password=" + password + ", createDate=" + createDate + ", status=" + status + ", name=" + name + ", sex=" + sex + ", dob=" + dob + ", phone=" + phone + ", email=" + email + ", address=" + address + ", groupName=" + groupName + ", roleName=" + roleName + '}';
    }


    
}
